version: '3.9'

services:
  # db:
  #   image: postgres:16-alpine
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_USER: finsight
  #     POSTGRES_PASSWORD: finsight
  #     POSTGRES_DB: finsight
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   ports:
  #     - '5432:5432'

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: finsight-server
    restart: unless-stopped
    depends_on:
      - cache
    env_file:
      - ./server/.env
    environment:
      CACHE_SERVER: ${CACHE_HOST}:${CACHE_PORT}
      DATABASE_URL: ${DATABASE_URL}
      GROQ_API_KEY: ${GROQ_API_KEY}
      PORT: ${PORT}
    ports:
      - '3001:3001'

  # client:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   depends_on:
  #     - server
  #   ports:
  #     - '5173:80'

  cache:
    image: memcached:alpine
    container_name: finsight-cache
    ports:
      - "11211:11211"
    restart: unless-stopped
    command: ["memcached", "-m", "64"]
